/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
    },
    extend: {
      colors: {
        primary: {
          50: "#f7fbfd",
          100: "#edf7fb",
          200: "#dcecf4",
          300: "#c5e2eb",
          400: "#b4e1eb",
          500: "#9ed0de",
          600: "#78a4cb",
          700: "#5f88af",
          800: "#4d6e92",
          900: "#405b78",
          DEFAULT: "#78a4cb",
          foreground: "#ffffff",
        },
        secondary: {
          50: "#fdf7fc",
          100: "#f9eaf6",
          200: "#f2d6eb",
          300: "#e8c5e5",
          400: "#f19ed2",
          500: "#e07bbf",
          DEFAULT: "#e8c5e5",
          foreground: "#5b3a53",
        },
        sidebar: {
          DEFAULT: "#fdfcff",
          foreground: "#4b3f49",
          hover: "#f6edf7",
          active: "#eef7fb",
          "active-foreground": "#2f2a33",
          border: "#e8dce7",
        },
        border: "#e8dce7",
        input: "#e8dce7",
        ring: "#78a4cb",
        background: "#fcfcfe",
        foreground: "#4b3f49",
        card: { DEFAULT: "#ffffff", foreground: "#4b3f49" },
        popover: { DEFAULT: "#ffffff", foreground: "#4b3f49" },
        muted: { DEFAULT: "#f8f3f7", foreground: "#7c6d7e" },
        accent: { DEFAULT: "#10b981", foreground: "#ffffff" },
        destructive: { DEFAULT: "#ef4444", foreground: "#ffffff" },
        warning: { DEFAULT: "#f59e0b", foreground: "#ffffff" },
        success: { DEFAULT: "#22c55e", foreground: "#ffffff" },
      },
      borderRadius: {
        lg: "0.75rem",
        md: "0.5rem",
        sm: "0.375rem",
        xl: "1rem",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
